services:
  - type: web
    name: silentface-anti-spoofing
    runtime: python
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
